baseURL = 'http://thewrys.redbiblica.org/'
languageCode = 'en-us'
title = 'The Wry Family'
ShowBreadCrumbs = "true"
theme = "paige"
# themesDir = "/"
PublishDir = "docs"

copyright = "© The Wrys"
enablerobotstxt = true
languagecode = "en-us"
paginate = 50
timezone = "America/Los_Angeles"
titlecasestyle = "Go"

[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "News"
name = "News"
url = "/News/"
weight = 20

#[[languages.en.menu.main]]
#identifier = "layouts"
#name = "Layouts"
#url = "/layouts/"
#weight = 30

#[[languages.en.menu.main]]
#identifier = "shortcodes"
#name = "Shortcodes"
#url = "/shortcodes/"
#weight = 40

#[[languages.en.menu.main]]
#identifier = "customization"
#name = "Customization"
#url = "/customization/"
#weight = 50

#[[languages.en.menu.main]]
#identifier = "authors"
#name = "Authors"
#url = "/authors/"
#weight = 60

[[languages.en.menu.main]]
#identifier = "Articles"
#name = "Articles"
#url = "/articles/"
#weight = 70

#[[languages.en.menu.main]]
#identifier = "categories"
#name = "Categories"
#url = "/categories/"
#weight = 80

#[[languages.en.menu.main]]
#identifier = "tags"
#name = "Tags"
#url = "/tags/"
#weight = 90

[[languages.en.menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 100

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

#[[module.imports]]
#path = "github.com/willfaught/paige"

[outputs]
home = ["html", "json", "rss"]

[params]
    custom_css = ["css/custom.css"]

[params.authors.will-faught]
name = "The Wrys"

#[params.paige.git]
#commit_url = "https://github.com/willfaught/paige/commit/%s"

[taxonomies]
#author = "authors"
#category = "categories"
#series = "series"
tag = "tags"
